version: '2'
services:
  db:
    image: mysql
    expose:
      - "3306"
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=fishpool
      - MYSQL_ROOT_PASSWORD=199666

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    links:
      - db